.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo10 - Debug ]----------"
	@cd "ejemplo10" && "$(MAKE)" -f  "ejemplo10.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo10 - Debug ]----------"
	@cd "ejemplo10" && "$(MAKE)" -f  "ejemplo10.mk" clean
